// Generated by tools/audio/make_audio.py: do not edit.
#ifndef SNC_AUDIO_H
#define SNC_AUDIO_H
#include <stdint.h>

extern const uint8_t snd_lobby[];  // 8-bit PCM
#define SND_LOBBY_BYTES 527520
#define SND_LOBBY_RATE 13379
#define SND_LOBBY_SAMPLES 527520
extern const uint8_t snd_game[];  // 8-bit PCM
#define SND_GAME_BYTES 653408
#define SND_GAME_RATE 13379
#define SND_GAME_SAMPLES 653408
extern const uint8_t snd_win[];  // 8-bit PCM
#define SND_WIN_BYTES 62272
#define SND_WIN_RATE 13379
#define SND_WIN_SAMPLES 62272
extern const uint8_t snd_lose[];  // 8-bit PCM
#define SND_LOSE_BYTES 51296
#define SND_LOSE_RATE 13379
#define SND_LOSE_SAMPLES 51296
extern const uint8_t snd_sfx_move[];  // 8-bit PCM
#define SND_SFX_MOVE_BYTES 6496
#define SND_SFX_MOVE_RATE 13379
#define SND_SFX_MOVE_SAMPLES 6496
extern const uint8_t snd_sfx_select[];  // 8-bit PCM
#define SND_SFX_SELECT_BYTES 6496
#define SND_SFX_SELECT_RATE 13379
#define SND_SFX_SELECT_SAMPLES 6496
extern const uint8_t snd_sfx_back[];  // 8-bit PCM
#define SND_SFX_BACK_BYTES 6496
#define SND_SFX_BACK_RATE 13379
#define SND_SFX_BACK_SAMPLES 6496
extern const uint8_t snd_sfx_place[];  // 8-bit PCM
#define SND_SFX_PLACE_BYTES 6496
#define SND_SFX_PLACE_RATE 13379
#define SND_SFX_PLACE_SAMPLES 6496
extern const uint8_t snd_sfx_capture[];  // 8-bit PCM
#define SND_SFX_CAPTURE_BYTES 10752
#define SND_SFX_CAPTURE_RATE 13379
#define SND_SFX_CAPTURE_SAMPLES 10752
extern const uint8_t snd_sfx_turn[];  // 8-bit PCM
#define SND_SFX_TURN_BYTES 10752
#define SND_SFX_TURN_RATE 13379
#define SND_SFX_TURN_SAMPLES 10752
extern const uint8_t snd_sfx_error[];  // 8-bit PCM
#define SND_SFX_ERROR_BYTES 6496
#define SND_SFX_ERROR_RATE 13379
#define SND_SFX_ERROR_SAMPLES 6496
extern const uint8_t snd_sfx_start[];  // 8-bit PCM
#define SND_SFX_START_BYTES 13440
#define SND_SFX_START_RATE 13379
#define SND_SFX_START_SAMPLES 13440

#endif
