// Generated by tools/audio/make_audio.py: do not edit.
#ifndef SNC_AUDIO_H
#define SNC_AUDIO_H
#include <stdint.h>

extern const uint8_t snd_lobby[];  // IMA-ADPCM
#define SND_LOBBY_BYTES 338036
#define SND_LOBBY_RATE 16384
#define SND_LOBBY_SAMPLES 676063
extern const uint8_t snd_game[];  // IMA-ADPCM
#define SND_GAME_BYTES 421348
#define SND_GAME_RATE 16384
#define SND_GAME_SAMPLES 842688
extern const uint8_t snd_win[];  // 8-bit PCM
#define SND_WIN_BYTES 88376
#define SND_WIN_RATE 16384
#define SND_WIN_SAMPLES 88376
extern const uint8_t snd_lose[];  // 8-bit PCM
#define SND_LOSE_BYTES 69732
#define SND_LOSE_RATE 16384
#define SND_LOSE_SAMPLES 69732
extern const uint8_t snd_sfx_move[];  // 8-bit PCM
#define SND_SFX_MOVE_BYTES 7864
#define SND_SFX_MOVE_RATE 16384
#define SND_SFX_MOVE_SAMPLES 7864
extern const uint8_t snd_sfx_select[];  // 8-bit PCM
#define SND_SFX_SELECT_BYTES 9832
#define SND_SFX_SELECT_RATE 16384
#define SND_SFX_SELECT_SAMPLES 9832
extern const uint8_t snd_sfx_back[];  // 8-bit PCM
#define SND_SFX_BACK_BYTES 7864
#define SND_SFX_BACK_RATE 16384
#define SND_SFX_BACK_SAMPLES 7864
extern const uint8_t snd_sfx_place[];  // 8-bit PCM
#define SND_SFX_PLACE_BYTES 2356
#define SND_SFX_PLACE_RATE 16384
#define SND_SFX_PLACE_SAMPLES 2356
extern const uint8_t snd_sfx_capture[];  // 8-bit PCM
#define SND_SFX_CAPTURE_BYTES 7856
#define SND_SFX_CAPTURE_RATE 16384
#define SND_SFX_CAPTURE_SAMPLES 7856
extern const uint8_t snd_sfx_turn[];  // 8-bit PCM
#define SND_SFX_TURN_BYTES 13108
#define SND_SFX_TURN_RATE 16384
#define SND_SFX_TURN_SAMPLES 13108
extern const uint8_t snd_sfx_error[];  // 8-bit PCM
#define SND_SFX_ERROR_BYTES 7864
#define SND_SFX_ERROR_RATE 16384
#define SND_SFX_ERROR_SAMPLES 7864
extern const uint8_t snd_sfx_start[];  // 8-bit PCM
#define SND_SFX_START_BYTES 12228
#define SND_SFX_START_RATE 16384
#define SND_SFX_START_SAMPLES 12228

#endif
